version: '2'
services:
    test:
        image: silintl/php7:7.2
        volumes:
            - ./:/data
        working_dir: /data
        env_file:
            - ./local.env
        command: ["true"]

