name: Unit Tests

on:
  push:

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          ini-values: variables_order=EGPCS
          tools: composer, phpunit
          
      - name: Unit Tests
        run: |
          composer install
          ./vendor/bin/phpunit --process-isolation tests/
